### PR TITLE
feat: Retrieve user transaction history #26

### PR DESCRIPTION
**Pull request by omsant02**
Implemented a function to retrieve user transaction history for display on the portfolio page. Added relevant tests.

## Summary by CodeRabbit

- **New Features**
	- Introduced transaction recording for deposits and withdrawals.
	- Added a public function to retrieve a user's transaction history.
	- Enhanced event logging with a new `TransactionRecorded` variant.

- **Bug Fixes**
	- Improved accuracy in withdrawal event recording.

- **Documentation**
	- Updated interfaces to reflect new transaction functionalities.

### CODE REVIEW

**Review by Dprof-in-tech — CHANGES_REQUESTED** [review]
There are changes suggested by Codeabbit ai, please implement them. also remove the packge-lock.json from this PR, fix your merge conflicts and we are good to go.

**Comment by Dprof-in-tech** [comment]
Also you might want to make the trnsaction history not only return the token and the amount but also build an indexer so that the details of the transaction are detailed enough.

PS: please return a transaction hash that can be viewed on an explorer.

**Comment by Dprof-in-tech** [comment]
https://www.streamingfast.io/blog/starknet-gets-substreams-subgraph-studio-support

https://docs.substreams.dev/documentation/how-to-guides/starknet


you can use this to build the below idea for this transaction history


Concerning the issue #26 and general user history eish, is it possible to setup a substream on thegraph, and provide a DB sink like Postgre? then the DB can also be indexed too to make queries faster?

This is a suggestion we would love to explore. Also, if you are not in our telegram group, please join up with the below link so we can sync faster


https://t.me/+p7vbt9n01blhZDY0

**Comment by omsant02** [comment]
thanks for sharing the resources, i'll look into it

**Review by Dprof-in-tech — APPROVED** [review]

**Pull request merged**
