### PR TITLE
feat/retrieve user assets

### PR DESCRIPTION
**Pull request by casweeney**
- Added `get_user_assets()` function signature in the `IPeerProtocol` interface.
- Updated `PeerProtocol` storage structure.
- Modified `add_supported_token()` to append `token_address` in the `supported_token_list` storage vector.
- Implemented `get_user_assets()` function.
- Tested `get_user_assets()` function.

## Summary by CodeRabbit

- **New Features**
	- Introduced a `get_user_assets` method to retrieve user-specific asset information.
	- Enhanced tracking of user interactions with tokens through new storage fields.
  
- **Bug Fixes**
	- Updated event emission syntax for the `withdraw` function for consistency.

- **Tests**
	- Added a new test function for validating the `get_user_assets` method.
	- Modified existing tests to improve accuracy with updated token references.

- **Chores**
	- Removed the mock token implementation as part of code cleanup.

### CODE REVIEW

**Comment by kfastov** [comment]
Hi @casweeney ! I am not the maintainer but I guess `mock_token1.cairo` and `mock_token2.cairo` files are missing from the code 😊

**Comment by kfastov** [comment]
Also you can deploy the same token twice if you need:
https://github.com/Dprof-in-tech/peer-on-strk/blob/36d854024b5f0208d8617ff6988ed8f4e1edcd5a/contracts/tests/test_peer_protocol.cairo#L164-L165

**Comment by casweeney** [comment]
> Hi @casweeney ! I am not the maintainer but I guess `mock_token1.cairo` and `mock_token2.cairo` files are missing from the code 😊

Yes, they are missing because my PR is yet to be merged. You have to wait for the maintainer to merge my code first. Your issue is kinda depended on mine.

**Comment by casweeney** [comment]
> Also you can deploy the same token twice if you need:
> 
> https://github.com/Dprof-in-tech/peer-on-strk/blob/36d854024b5f0208d8617ff6988ed8f4e1edcd5a/contracts/tests/test_peer_protocol.cairo#L164-L165

Oh I see, thanks Brother. I have updated my test files and also deleted the extra mock token I created.

**Review by Dprof-in-tech — APPROVED** [review]
Thank you. also Thank you Fastov for helping out

**Pull request merged**
